services:
  # PostgreSQL Database
  - type: pserv
    name: air-quality-postgres
    env: docker
    plan: standard
    region: oregon
    dockerfilePath: ./Dockerfile.postgres
    envVars:
      - key: POSTGRES_DB
        value: air_quality_db
      - key: POSTGRES_USER
        value: airquality
      - key: POSTGRES_PASSWORD
        generateValue: true
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10

  # Backend API Service (Production with ML Models)
  - type: web
    name: aqi-prediction-api
    env: python
    plan: standard
    region: oregon
    buildCommand: pip install -r requirements.txt && python -c "from backend.database.db_manager import init_database; init_database()"
    startCommand: python backend/production_api.py
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: air-quality-postgres
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://aqi-prediction-frontend.onrender.com
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: IQAIR_API_KEY
        sync: false
      - key: CPCB_API_KEY
        sync: false
    autoDeploy: true

  # Frontend Service (React + Vite)
  - type: web
    name: aqi-prediction-frontend
    env: static
    plan: starter
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: VITE_API_URL
        value: https://aqi-prediction-api.onrender.com
    autoDeploy: true

  # Automated Data Collection & Prediction Worker
  - type: worker
    name: aqi-automated-scheduler
    env: python
    plan: starter
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python automated_scheduler.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: air-quality-postgres
          property: connectionString
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: IQAIR_API_KEY
        sync: false
      - key: CPCB_API_KEY
        sync: false
    autoDeploy: true

databases:
  - name: air-quality-postgres
    databaseName: air_quality_db
    user: airquality
    plan: standard
    region: oregon
